{
  lib,
  stdenv,
  stdenvNoCC,
  fetchurl,
  autoPatchelfHook,
  makeWrapper,
  installShellFiles,
  git,
  symlinkJoin,
  # Generated by ./update.py — do not hand-edit.
  sources ? builtins.fromJSON (builtins.readFile ./sources.json),
}:

let
  # Everything that is a human judgement rather than a fact about a release
  # lives here; everything in sources.json is machine-generated.
  toolMeta = {
    kata = {
      description = "Local-first issue tracking for AI-assisted software work, with an agent-friendly CLI and TUI";
      license = lib.licenses.mit;
    };
    forge = {
      description = "Local-first maintainer console with built-in agent workspaces for PRs, issues and CI";
      # Elastic License 2.0. nixpkgs marks this free = false, and since
      # `redistributable` defaults to `free`, it inherits redistributable =
      # false too — despite ELv2 explicitly permitting distribution. The
      # flake scopes an allowUnfreePredicate to this one package.
      license = lib.licenses.elastic20;
      # Turns any item into a git worktree session.
      runtimeDeps = [ git ];
    };
    roborev = {
      description = "Continuous background code review database for coding agents";
      license = lib.licenses.mit;
      # Reviews git commits; shells out constantly.
      runtimeDeps = [ git ];
    };
    msgvault = {
      description = "Offline archive, search and analytics over email and chat history";
      license = lib.licenses.mit;
    };
    docbank = {
      description = "Local-first system of record for documents (PDFs, images, text) for you and your agents";
      license = lib.licenses.asl20;
    };
    kwt = {
      description = "Terminal dashboard and scriptable CLI for managing git worktrees";
      license = lib.licenses.asl20;
      runtimeDeps = [ git ];
    };
    agentsview = {
      description = "Local-first session search, analytics and token statistics for 20+ coding agents";
      license = lib.licenses.mit;
    };
  };

  mkKennTool =
    repo: src:
    let
      info = toolMeta.${repo};
      runtimeDeps = info.runtimeDeps or [ ];
      system = stdenv.hostPlatform.system;
      plat =
        src.platforms.${system}
          or (throw "kenn-io/${repo} v${src.version} publishes no binary for ${system}");
      # kenn-forge has no `completion` subcommand upstream; the rest do.
      hasCompletion = repo != "forge";
    in
    stdenvNoCC.mkDerivation {
      pname = src.binary;
      inherit (src) version;

      src = fetchurl {
        url = "https://github.com/kenn-io/${repo}/releases/download/v${src.version}/${plat.asset}";
        inherit (plat) hash;
      };

      # Layouts differ: kata and kwt ship LICENSE/README beside the binary
      # (so the unpacker sees multiple top-level entries and needs "."),
      # forge ships the bare binary.
      sourceRoot = ".";

      nativeBuildInputs =
        lib.optionals stdenv.hostPlatform.isLinux [ autoPatchelfHook ]
        ++ lib.optionals (runtimeDeps != [ ]) [ makeWrapper ]
        ++ lib.optionals hasCompletion [ installShellFiles ];

      # Measured on linux/amd64 at the pinned versions:
      #   static:  kata, kenn-forge, roborev, kwt
      #   dynamic: docbank (libc, libm)
      #            agentsview, msgvault (+ libstdc++/libgcc, via cgo sqlite/duckdb)
      # glibc comes for free, so cc.cc.lib is the only addition. The hook is
      # applied unconditionally and skips the statically linked binaries.
      buildInputs = lib.optionals stdenv.hostPlatform.isLinux [ stdenv.cc.cc.lib ];

      installPhase = ''
        runHook preInstall
        found="$(find . -type f -name '${src.binary}' -print -quit)"
        if [ -z "$found" ]; then
          echo "binary '${src.binary}' not found in ${plat.asset}" >&2
          exit 1
        fi
        install -Dm755 "$found" "$out/bin/${src.binary}"
        runHook postInstall
      '';

      postFixup = ''
        ${lib.optionalString (stdenv.hostPlatform.isLinux && hasCompletion) ''
          # autoPatchelfHook's own patching runs via postFixupHooks, which
          # fires after this attribute — too late to exec a dynamic binary
          # below. Patching is idempotent, so run it early ourselves too.
          autoPatchelf -- "$out"
        ''}
        ${lib.optionalString (runtimeDeps != [ ]) ''
          # --suffix, not --prefix: if the user has their own git on PATH it
          # wins, and ours is only the fallback.
          wrapProgram "$out/bin/${src.binary}" \
            --suffix PATH : ${lib.makeBinPath runtimeDeps}
        ''}
        ${lib.optionalString hasCompletion ''
          # kwt needs a writable $HOME for any subcommand. Each <(...) below
          # runs concurrently, and two kwt processes racing to initialize a
          # config file under the same fresh $HOME lose the race with "file
          # exists" — give each its own $HOME.
          installShellCompletion --cmd ${src.binary} \
            --bash <(HOME="$(mktemp -d)" "$out/bin/${src.binary}" completion bash) \
            --fish <(HOME="$(mktemp -d)" "$out/bin/${src.binary}" completion fish) \
            --zsh <(HOME="$(mktemp -d)" "$out/bin/${src.binary}" completion zsh)
        ''}
      '';

      # All seven support a `version` subcommand (they do NOT all accept
      # --version, which is why this is not versionCheckHook's default).
      doInstallCheck = stdenv.buildPlatform.canExecute stdenv.hostPlatform;
      installCheckPhase = ''
        runHook preInstallCheck
        # kwt initialises its config directory under $HOME before it will run
        # any subcommand, and the sandbox points HOME at /homeless-shelter,
        # which is deliberately unwritable — so `kwt version` dies with
        # "failed to create config directory". The other six do not care, but
        # a throwaway HOME is harmless for them and keeps this phase uniform.
        export HOME="$(mktemp -d)"
        "$out/bin/${src.binary}" version
        runHook postInstallCheck
      '';

      meta = {
        inherit (info) description license;
        homepage = "https://github.com/kenn-io/${repo}";
        downloadPage = "https://github.com/kenn-io/${repo}/releases";
        mainProgram = src.binary;
        sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
        platforms = builtins.attrNames src.platforms;
      };
    };

  tools = lib.mapAttrs' (repo: src: {
    name = src.binary;
    value = mkKennTool repo src;
  }) sources;

  mkToolkit =
    name: paths:
    symlinkJoin {
      inherit name paths;
      meta = {
        description = "The kenn-io toolkit";
        platforms = lib.platforms.unix;
      };
    };

  freeTools = lib.attrValues (lib.filterAttrs (n: _: n != "kenn-forge") tools);
in
tools
// {
  # kenn-forge is deliberately absent. The flake already scopes an
  # allowUnfreePredicate so it *builds*, but shipping an Elastic-licensed
  # binary in the default target without the user asking is a policy decision
  # they should make, not one this flake should make silently.
  kenn-io-toolkit = mkToolkit "kenn-io-toolkit" freeTools;
  kenn-io-toolkit-all = mkToolkit "kenn-io-toolkit-all" (freeTools ++ [ tools.kenn-forge ]);
}
