{
  lib,
  buildGoModule,
  buildNpmPackage,
  fetchFromGitHub,
  fetchurl,
  cacert,
  bun2nix,
  nodejs,
  runCommand,
  sqlite,
  # Generated by ./update.py --source (ADR-0007) — do not hand-edit. Mirrors
  # how packages.nix takes `sources` from sources.json: this file holds the
  # hand-written per-tool DERIVATION shape (which build system, which quirks),
  # source-builds.json holds only the generated per-tool FACTS (rev, and
  # whatever hashes that shape needs).
  sourceBuilds ? builtins.fromJSON (builtins.readFile ./source-builds.json),
}:

# Proof of concept, per ADR-0007: build a kenn-io tool directly from a git
# revision instead of an upstream release binary. packages.nix's mkKennTool
# only ever fetches a tagged release asset — this is deliberately a SEPARATE,
# narrower path, not a mode bolted onto mkKennTool, because a source build is
# a different reproducibility contract (pinned to a commit + a Go module
# graph, not to a checksum-verified published artifact).
#
# Only kwt and docbank are wired up (ADR-0007 decision 1: tools graduate one
# at a time, not as a batch). kwt has no cgo dependencies and no embedded
# frontend — the cheapest shape to prove the mechanism on. docbank is the
# second proof, chosen for the opposite shape: CGO_ENABLED=1 (mattn/go-sqlite3)
# plus an npm-built Svelte frontend embedded via go:embed. Extending this to
# the remaining five tools is real, uneven work — see nix/kenn/README.md's
# "Building from source" section and ADR-0007's effort table before assuming
# it generalizes for free. In particular kata/forge/msgvault embed a **bun**
# frontend instead of npm, and forge additionally carries a Rust component.
let
  mkKennToolFromSource =
    {
      repo,
      binary,
      subPackage ? "cmd/${binary}",
    }:
    let
      pin = sourceBuilds.${repo};
    in
    buildGoModule {
      pname = binary;
      version = pin.rev;
      vendorHash = pin.vendorHash;

      src = fetchFromGitHub {
        owner = "kenn-io";
        inherit repo;
        rev = pin.rev;
        hash = pin.srcHash;
      };

      subPackages = [ subPackage ];

      # Matches the upstream release build: no ldflags-injected version string,
      # since "version" here is a commit, not a semver release.
      doCheck = false;

      # Same as mkKennTool's installCheckPhase in packages.nix: kwt needs a
      # writable $HOME to initialise its config directory before it will run
      # any subcommand, and the sandbox's $HOME is deliberately unwritable.
      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/${binary}" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/${repo}, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/${repo}";
        mainProgram = binary;
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };

  # docbank: tool #2 (ADR-0007 decision 1), chosen specifically because it
  # exercises what kwt didn't — CGO_ENABLED=1 (mattn/go-sqlite3, no external
  # sqlite header needed, unlike msgvault's sqlite-vec) and an npm-built
  # Svelte frontend embedded via go:embed. The frontend also pulls
  # @kenn-io/kit-ui straight from a git commit (not the npm registry) in
  # frontend/package-lock.json — buildNpmPackage's fetchNpmDeps handles a
  # resolved git+https dependency fine, it just needs git reachable during
  # that fetch, which is worth remembering if this ever breaks.
  docbank-from-source =
    let
      pin = sourceBuilds.docbank;
      docbankSrc = fetchFromGitHub {
        owner = "kenn-io";
        repo = "docbank";
        rev = pin.rev;
        hash = pin.srcHash;
      };
      frontend = buildNpmPackage {
        pname = "docbank-frontend";
        version = pin.rev;
        src = "${docbankSrc}/frontend";
        npmDepsHash = pin.npmDepsHash;
        # frontend/package.json depends on @kenn-io/kit-ui straight from a git
        # commit rather than the npm registry. That has install scripts but no
        # lockfile of its own, which prefetch-npm-deps refuses by default.
        forceGitDeps = true;
        # The git-fetched kit-ui dependency leaves root-owned files in the
        # prefetched cache (the same "unsandboxed builder as fake root"
        # surprise documented in this flake's own README, for kwt's config
        # directory) — npm then refuses to write into it unless told the
        # cache is writable.
        makeCacheWritable = true;
        # "vp build" (vite-plus, a Rust-implemented Vite) initialises an HTTP
        # client unconditionally even for a fully offline build, and panics if
        # it can't find a CA bundle — nixpkgs' sandbox doesn't set one by
        # default. Point it at cacert's; nothing here should ever need it to
        # actually make a request.
        SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";
        # "vp build" (vite-plus) — the frontend's own package.json aliases
        # vite to it. No install step: docbank's Makefile only ever runs
        # `npm ci && npm run build`, never `npm install`.
        npmBuildScript = "build";
        installPhase = ''
          runHook preInstall
          mkdir -p "$out"
          cp -R dist/. "$out/"
          runHook postInstall
        '';
      };
    in
    buildGoModule {
      pname = "docbank";
      version = pin.rev;
      src = docbankSrc;

      vendorHash = pin.vendorHash;

      subPackages = [ "cmd/docbank" ];
      tags = [ "fts5" ]; # SQLite FTS5, matches the upstream BUILD_TAGS
      env.CGO_ENABLED = 1; # mattn/go-sqlite3 links C; no cgo-free build exists
      doCheck = false;

      # buildGoModule's internal vendor-fetch derivation (the "go-modules"
      # FOD) inherits preBuild too, by default — it doesn't need the frontend
      # at all, so without this override it grows a pointless dependency edge
      # on `frontend` (a failed frontend build cascades into a "go-modules
      # dependency failed" that has nothing to do with Go modules). Same fix
      # msgvault's own nix/package.nix uses for the same reason.
      overrideModAttrs = _: {
        preBuild = "";
      };

      # Mirrors the Makefile's `frontend` target: empty internal/web/dist
      # (keeping the go:embed stub) and copy the built SPA in before `go build`
      # ever runs, so the binary embeds the real frontend, not the stub.
      preBuild = ''
        find internal/web/dist -mindepth 1 ! -name .keep -exec rm -rf {} +
        cp -R ${frontend}/. internal/web/dist/
      '';

      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/docbank" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/docbank, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/docbank";
        mainProgram = "docbank";
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };

  # agentsview: tool #3, same docbank shape (CGO_ENABLED=1 + npm/Svelte
  # frontend) plus three quirks docbank never hit:
  #   - the cgo sqlite header must come from the VENDORED mattn/go-sqlite3
  #     module (its own amalgamation header), not a system sqlite package —
  #     upstream's own Makefile warns that a system header drifts from what
  #     the pinned go-sqlite3 version actually ships, and that CGO_CFLAGS
  #     must restate "-O2 -g" or the amalgamation compiles unoptimized.
  #   - `make build` depends on a network fetch (a pinned, hash-verified
  #     LiteLLM pricing snapshot) that has no place in a sandboxed build;
  #     fetched here as its own fixed-output derivation instead.
  #   - the frontend's `i18n:compile` step (paraglide-js) is NOT part of
  #     `npm run build` and its output is not committed — must run first or
  #     the Svelte build fails on a missing generated import.
  agentsview-from-source =
    let
      pin = sourceBuilds.agentsview;
      agentsviewSrc = fetchFromGitHub {
        owner = "kenn-io";
        repo = "agentsview";
        rev = pin.rev;
        hash = pin.srcHash;
      };
      # Pinned inside agentsview's own source (internal/pricing/cmd/litellm-
      # snapshot) as an immutable git ref + sha256, independent of pin.rev —
      # only needs updating if agentsview itself repins its snapshot.
      pricingSnapshot = fetchurl {
        url = "https://raw.githubusercontent.com/kenn-io/agentsview/db257992fb8e3048af8c1cec9da738c28b4fe603/litellm_snapshot.json.gz";
        hash = "sha256-Dom2Nsz4WO2/laP2GIR2tuq2zyH2bRamXCGEIp74HL4=";
      };
      frontend = buildNpmPackage {
        pname = "agentsview-frontend";
        version = pin.rev;
        src = "${agentsviewSrc}/frontend";
        npmDepsHash = pin.npmDepsHash;
        # Same @kenn-io/kit-ui git+https dependency as docbank.
        forceGitDeps = true;
        makeCacheWritable = true;
        SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";
        # `npm run build` alone fails: paraglide's generated src/lib/paraglide
        # isn't committed and nothing but `precheck` (a hook `build` never
        # fires) runs `i18n:compile` for it.
        preBuild = "npm run i18n:compile";
        npmBuildScript = "build";
        installPhase = ''
          runHook preInstall
          mkdir -p "$out"
          cp -R dist/. "$out/"
          runHook postInstall
        '';
      };
    in
    buildGoModule {
      pname = "agentsview";
      version = pin.rev;
      src = agentsviewSrc;

      vendorHash = pin.vendorHash;
      # buildGoModule's default `go mod vendor` step disagrees with itself on
      # agentsview's dependency graph ("X is explicitly required in go.mod,
      # but not marked as explicit in vendor/modules.txt") — the same fix
      # msgvault's own nix/package.nix uses for the same shape of error:
      # resolve modules via GOPROXY against the fetched cache instead of
      # materializing and vendor-checking a tree.
      proxyVendor = true;
      # The go-modules FOD inherits preBuild too (see docbank's comment on the
      # same override) — here that would run `go list -m` before the vendor
      # fetch has anything to resolve, failing the FOD outright rather than
      # just wastefully succeeding.
      overrideModAttrs = _: {
        preBuild = "";
      };

      subPackages = [ "cmd/agentsview" ];
      tags = [ "fts5" ];
      env.CGO_ENABLED = 1; # mattn/go-sqlite3 links C; no cgo-free build exists
      doCheck = false;

      preBuild = ''
        # Mirrors the Makefile's sqlite-vec-header target exactly: `go list
        # -m -f '{{.Dir}}'` only reports a module's extracted directory once
        # something has actually extracted it — merely being in the download
        # cache (which the go-modules FOD already populated) isn't enough —
        # so `go mod download` here forces that extraction first.
        go mod download github.com/mattn/go-sqlite3
        mkdir -p .sqlite-include
        install -m0644 "$(go list -m -f '{{.Dir}}' github.com/mattn/go-sqlite3)/sqlite3-binding.h" \
          .sqlite-include/sqlite3.h
        export CGO_CFLAGS="-O2 -g -I$PWD/.sqlite-include''${CGO_CFLAGS:+ $CGO_CFLAGS}"

        find internal/web/dist -mindepth 1 ! -name .keep -exec rm -rf {} +
        cp -R ${frontend}/. internal/web/dist/

        mkdir -p internal/pricing/snapshot
        cp ${pricingSnapshot} internal/pricing/snapshot/litellm_snapshot.json.gz
      '';

      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/agentsview" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/agentsview, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/agentsview";
        mainProgram = "agentsview";
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };

  # msgvault: tool #4, the first bun-frontend tool. msgvault's own
  # nix/package.nix already solves bun vendoring with nix-community/bun2nix —
  # this closely adapts that proven recipe rather than reinventing it,
  # simplified in one way: msgvault's own flake repins an exact bun version to
  # protect ITS OWN release cadence against bun2nix drift; a single
  # source-build entry here doesn't carry that risk, so it uses bun2nix's
  # stock nixpkgs-bun default instead.
  #
  # Unlike npmDepsHash, there is no separate "bun deps hash" to discover:
  # bun2nix works from a COMMITTED web/bun.nix (bun2nix's own lockfile
  # equivalent, generated upstream, not by us) inside the fetched source tree
  # — its per-package hashes are already covered by srcHash, so this tool
  # needs no extra SOURCE_BUILD_TOOLS field beyond the universal two.
  msgvault-from-source =
    let
      pin = sourceBuilds.msgvault;
      msgvaultSrc = fetchFromGitHub {
        owner = "kenn-io";
        repo = "msgvault";
        rev = pin.rev;
        hash = pin.srcHash;
      };
      # Bun's copyfile backend can install incomplete packages when
      # fetchBunDeps' cache entries are backed by symlinks — materialize the
      # cache as regular files before the sandboxed install consumes it.
      bunDeps =
        let
          base = bun2nix.fetchBunDeps { bunNix = "${msgvaultSrc}/web/bun.nix"; };
        in
        runCommand "msgvault-bun-deps" { } ''
          mkdir -p "$out/share/bun-cache"
          cp -RL ${base}/share/bun-cache/. "$out/share/bun-cache/"
          chmod -R u+w "$out/share/bun-cache"
        '';
    in
    buildGoModule {
      pname = "msgvault";
      version = pin.rev;
      src = msgvaultSrc;

      vendorHash = pin.vendorHash;
      proxyVendor = true; # same go mod vendor self-disagreement as agentsview

      inherit bunDeps;
      bunRoot = "web";
      bunInstallFlags = [
        "--linker=hoisted"
        "--backend=copyfile"
      ];
      # The frontend dependencies do not need install scripts. A second Linux
      # Bun install can remove package binaries created by the offline
      # install.
      dontRunLifecycleScripts = true;
      dontUseBunBuild = true;
      dontUseBunCheck = true;
      dontUseBunInstall = true;

      nativeBuildInputs = [
        bun2nix.hook
        nodejs
      ];
      # Same preBuild-leaks-into-go-modules issue as docbank/agentsview, plus
      # bun2nix's own hook has no business running for a plain Go module fetch.
      overrideModAttrs = _: previous: {
        nativeBuildInputs = builtins.filter (
          input: (input.name or "") != "bun2nix-hook"
        ) previous.nativeBuildInputs;
        preBuild = "";
      };

      preBuild = ''
        pushd web
        bun node_modules/openapi-typescript/bin/cli.js ../api/openapi.yaml --output src/lib/api/generated/schema.d.ts
        bun node_modules/vite/bin/vite.js build
        popd
        mkdir -p internal/web/dist
        find internal/web/dist -mindepth 1 -maxdepth 1 ! -name stub.html -exec rm -rf {} +
        cp -R web/dist/. internal/web/dist/
        bun scripts/check-web-assets.mjs
      '';

      subPackages = [ "cmd/msgvault" ];
      env.CGO_ENABLED = 1; # mattn/go-sqlite3, duckdb-go, sqlite-vec-go-bindings all link C
      # sqlite-vec-go-bindings does `#include "sqlite3.h"` but ships no sqlite
      # source — provide the system header via buildInputs (msgvault's own
      # choice; agentsview instead builds against its vendored go-sqlite3
      # header specifically to avoid drift — two different tools, two
      # different tradeoffs, both correct for their own upstream).
      buildInputs = [ sqlite ];
      tags = [
        "fts5"
        "sqlite_vec"
      ];
      doCheck = false;

      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/msgvault" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/msgvault, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/msgvault";
        mainProgram = "msgvault";
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };
in
{
  inherit mkKennToolFromSource;

  kwt-from-source = mkKennToolFromSource {
    repo = "kwt";
    binary = "kwt";
  };

  inherit docbank-from-source;
  inherit agentsview-from-source;
  inherit msgvault-from-source;
}
