{
  lib,
  buildGoModule,
  buildNpmPackage,
  fetchFromGitHub,
  cacert,
  # Generated by ./update.py --source (ADR-0007) — do not hand-edit. Mirrors
  # how packages.nix takes `sources` from sources.json: this file holds the
  # hand-written per-tool DERIVATION shape (which build system, which quirks),
  # source-builds.json holds only the generated per-tool FACTS (rev, and
  # whatever hashes that shape needs).
  sourceBuilds ? builtins.fromJSON (builtins.readFile ./source-builds.json),
}:

# Proof of concept, per ADR-0007: build a kenn-io tool directly from a git
# revision instead of an upstream release binary. packages.nix's mkKennTool
# only ever fetches a tagged release asset — this is deliberately a SEPARATE,
# narrower path, not a mode bolted onto mkKennTool, because a source build is
# a different reproducibility contract (pinned to a commit + a Go module
# graph, not to a checksum-verified published artifact).
#
# Only kwt and docbank are wired up (ADR-0007 decision 1: tools graduate one
# at a time, not as a batch). kwt has no cgo dependencies and no embedded
# frontend — the cheapest shape to prove the mechanism on. docbank is the
# second proof, chosen for the opposite shape: CGO_ENABLED=1 (mattn/go-sqlite3)
# plus an npm-built Svelte frontend embedded via go:embed. Extending this to
# the remaining five tools is real, uneven work — see nix/kenn/README.md's
# "Building from source" section and ADR-0007's effort table before assuming
# it generalizes for free. In particular kata/forge/msgvault embed a **bun**
# frontend instead of npm, and forge additionally carries a Rust component.
let
  mkKennToolFromSource =
    {
      repo,
      binary,
      subPackage ? "cmd/${binary}",
    }:
    let
      pin = sourceBuilds.${repo};
    in
    buildGoModule {
      pname = binary;
      version = pin.rev;
      vendorHash = pin.vendorHash;

      src = fetchFromGitHub {
        owner = "kenn-io";
        inherit repo;
        rev = pin.rev;
        hash = pin.srcHash;
      };

      subPackages = [ subPackage ];

      # Matches the upstream release build: no ldflags-injected version string,
      # since "version" here is a commit, not a semver release.
      doCheck = false;

      # Same as mkKennTool's installCheckPhase in packages.nix: kwt needs a
      # writable $HOME to initialise its config directory before it will run
      # any subcommand, and the sandbox's $HOME is deliberately unwritable.
      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/${binary}" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/${repo}, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/${repo}";
        mainProgram = binary;
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };

  # docbank: tool #2 (ADR-0007 decision 1), chosen specifically because it
  # exercises what kwt didn't — CGO_ENABLED=1 (mattn/go-sqlite3, no external
  # sqlite header needed, unlike msgvault's sqlite-vec) and an npm-built
  # Svelte frontend embedded via go:embed. The frontend also pulls
  # @kenn-io/kit-ui straight from a git commit (not the npm registry) in
  # frontend/package-lock.json — buildNpmPackage's fetchNpmDeps handles a
  # resolved git+https dependency fine, it just needs git reachable during
  # that fetch, which is worth remembering if this ever breaks.
  docbank-from-source =
    let
      pin = sourceBuilds.docbank;
      docbankSrc = fetchFromGitHub {
        owner = "kenn-io";
        repo = "docbank";
        rev = pin.rev;
        hash = pin.srcHash;
      };
      frontend = buildNpmPackage {
        pname = "docbank-frontend";
        version = pin.rev;
        src = "${docbankSrc}/frontend";
        npmDepsHash = pin.npmDepsHash;
        # frontend/package.json depends on @kenn-io/kit-ui straight from a git
        # commit rather than the npm registry. That has install scripts but no
        # lockfile of its own, which prefetch-npm-deps refuses by default.
        forceGitDeps = true;
        # The git-fetched kit-ui dependency leaves root-owned files in the
        # prefetched cache (the same "unsandboxed builder as fake root"
        # surprise documented in this flake's own README, for kwt's config
        # directory) — npm then refuses to write into it unless told the
        # cache is writable.
        makeCacheWritable = true;
        # "vp build" (vite-plus, a Rust-implemented Vite) initialises an HTTP
        # client unconditionally even for a fully offline build, and panics if
        # it can't find a CA bundle — nixpkgs' sandbox doesn't set one by
        # default. Point it at cacert's; nothing here should ever need it to
        # actually make a request.
        SSL_CERT_FILE = "${cacert}/etc/ssl/certs/ca-bundle.crt";
        # "vp build" (vite-plus) — the frontend's own package.json aliases
        # vite to it. No install step: docbank's Makefile only ever runs
        # `npm ci && npm run build`, never `npm install`.
        npmBuildScript = "build";
        installPhase = ''
          runHook preInstall
          mkdir -p "$out"
          cp -R dist/. "$out/"
          runHook postInstall
        '';
      };
    in
    buildGoModule {
      pname = "docbank";
      version = pin.rev;
      src = docbankSrc;

      vendorHash = pin.vendorHash;

      subPackages = [ "cmd/docbank" ];
      tags = [ "fts5" ]; # SQLite FTS5, matches the upstream BUILD_TAGS
      env.CGO_ENABLED = 1; # mattn/go-sqlite3 links C; no cgo-free build exists
      doCheck = false;

      # Mirrors the Makefile's `frontend` target: empty internal/web/dist
      # (keeping the go:embed stub) and copy the built SPA in before `go build`
      # ever runs, so the binary embeds the real frontend, not the stub.
      preBuild = ''
        find internal/web/dist -mindepth 1 ! -name .keep -exec rm -rf {} +
        cp -R ${frontend}/. internal/web/dist/
      '';

      doInstallCheck = true;
      installCheckPhase = ''
        runHook preInstallCheck
        export HOME="$(mktemp -d)"
        "$out/bin/docbank" version
        runHook postInstallCheck
      '';

      meta = {
        description = "kenn-io/docbank, built from ${pin.rev} rather than a release binary";
        homepage = "https://github.com/kenn-io/docbank";
        mainProgram = "docbank";
        sourceProvenance = [ lib.sourceTypes.fromSource ];
      };
    };
in
{
  inherit mkKennToolFromSource;

  kwt-from-source = mkKennToolFromSource {
    repo = "kwt";
    binary = "kwt";
  };

  inherit docbank-from-source;
}
